site_name: "Paketti - A Framework / Firmware update for Renoise created by Esa Ruoho a.k.a. Lackluster"
docs_dir: "Documentation"  # Directory for your Markdown files and assets
theme:
  name: "material"  # Use Material theme for modern styling
  palette:
    primary: "indigo"
    accent: "indigo"
    toggle:
      icon: "material/brightness-4"
      name: "Switch to dark mode"
    scheme: "slate"  # Optional: Default to dark mode
extra_css:
  - dark-mode.css  # Link your dark mode CSS file here
extra_javascript:
  - dark-light-toggle.js  # Link JavaScript file for dark/light mode toggle

# Define the site navigation, linking each page in your Documentation folder
nav:
  - Home: index.md
  - Tools Menu: 01-ToolsMenu.md
  - Instrument Box: 02-InstrumentBox.md
  - Sample Editor: 03-SampleEditor.md
  - Pattern Editor: 04-PatternEditor.md
  - Automation: 05-Automation.md
  - Key Bindings: 22-KeyBindings.md
